#! /usr/bin/perl
# $XTermId: 256colres.pl,v 1.16 2007/06/08 23:58:37 tom Exp $
# -----------------------------------------------------------------------------
# this file is part of xterm
#
# Copyright 1999-2002,2007 by Thomas E. Dickey
# 
#                         All Rights Reserved
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE ABOVE LISTED COPYRIGHT HOLDER(S) BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the
# sale, use or other dealings in this Software without prior written
# authorization.
# -----------------------------------------------------------------------------

# Construct a header file defining default resources for the 256-color model
# of xterm.  This is modeled after the 256colors2.pl script.

# use the resources for colors 0-15 - usually more-or-less a
# reproduction of the standard ANSI colors, but possibly more
# pleasing shades

use strict;

our ( $line1, $line2, $line3 );
our ( $red, $green, $blue, $gray );
our ( $level, $code );

my $cpp_mode = (@ARGV && $ARGV[0] eq '--cpp');
my $cpp_n = 0;
my $cpp_total = 240;

if ($cpp_mode) {
    print "// Generated by: perl tools/256colres.pl --cpp > src/xterm_palette.h\n";
    print "// Source of truth: tools/256colres.pl (xterm 256-colour palette, slots 16-255)\n";
    print "#pragma once\n";
    print "#include <cstdint>\n\n";
    print "struct XtermColor { uint8_t r, g, b; };\n\n";
    print "// xterm_palette[i] is the RGB for xterm colour slot i + 16.\n";
    print "static const XtermColor xterm_palette[240] = {\n";
} else {
    print <<EOF;
/*
 * This header file was generated by $0
 */
/* \$XTermId\$ */

#ifndef included_256colres_h
#define included_256colres_h

EOF
}

$line1="COLOR_RES(\"%d\",";
$line2="\tscreen.Acolors[%d],";
$line3="\tDFT_COLOR(\"rgb:%2.2x/%2.2x/%2.2x\")),\n";

sub emit {
    my ($slot, $r, $g, $b) = @_;
    if ($cpp_mode) {
        my $sep = (++$cpp_n < $cpp_total) ? "," : " ";
        printf("    {%3d,%3d,%3d}%s  // slot %d\n", $r, $g, $b, $sep, $slot);
    } else {
        printf($line1, $slot);
        printf($line2, $slot);
        printf($line3, $r, $g, $b);
    }
}

# colors 16-231 are a 6x6x6 color cube
for ($red = 0; $red < 6; $red++) {
    for ($green = 0; $green < 6; $green++) {
	for ($blue = 0; $blue < 6; $blue++) {
	    $code = 16 + ($red * 36) + ($green * 6) + $blue;
	    emit($code,
		 ($red   ? ($red   * 40 + 55) : 0),
		 ($green ? ($green * 40 + 55) : 0),
		 ($blue  ? ($blue  * 40 + 55) : 0));
	}
    }
}

# colors 232-255 are a grayscale ramp, intentionally leaving out black and white
for ($gray = 0; $gray < 24; $gray++) {
    $level = ($gray * 10) + 8;
    $code = 232 + $gray;
    emit($code, $level, $level, $level);
}

if ($cpp_mode) {
    print "};\n";
} else {
    print <<EOF;

#endif /* included_256colres_h */
EOF
}
