if (EMSCRIPTEN)
    target_compile_definitions(numoria PUBLIC "PDC_WIDE")
    target_compile_definitions(numoria PUBLIC "PDC_FORCE_UTF8")
    target_compile_definitions(numoria PRIVATE "NUMORIA_PDC")
elseif ("${NUMORIA_BACKEND}" STREQUAL "pdc")
    target_compile_definitions(numoria PUBLIC "PDC_WIDE")
    target_compile_definitions(numoria PUBLIC "PDC_FORCE_UTF8")
    target_compile_definitions(numoria PRIVATE "NUMORIA_PDC")
    if ("${PDC_PORT}" STREQUAL "gl")
        target_compile_definitions(numoria PRIVATE "NUMORIA_GL")
    endif ()
elseif ("${NUMORIA_BACKEND}" STREQUAL "ncurses")
    target_compile_definitions(numoria PRIVATE "NUMORIA_NCURSES")
endif ()
