if ("${NUMORIA_CURSES}" IN_LIST NUMORIA_PDC_PLATFORMS)
    set(PDC_PLATFORM "${NUMORIA_CURSES}")
    include(ExternalProjects/PDCursesMod)
    add_dependencies(numoria pdcurses)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
elseif ("${NUMORIA_CURSES}" STREQUAL "ncurses")
    set(CURSES_NEED_NCURSES TRUE)
    find_package(Curses REQUIRED)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
else ()
    find_package(Curses REQUIRED)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
endif ()

include_directories("${CMAKE_BINARY_DIR}/${build_dir}")
