if ("${NUMORIA_CURSES}" IN_LIST NUMORIA_PDC_PLATFORMS)
    set(PDC_PLATFORM "${NUMORIA_CURSES}")
    include(ExternalProjects/PDCursesMod)
    add_dependencies(numoria pdcurses)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
elseif ("${NUMORIA_CURSES}" STREQUAL "ncurses")
    set(CURSES_NEED_NCURSES TRUE)
    find_package(Curses REQUIRED)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
elseif ("${NUMORIA_CURSES}" STREQUAL "browser")
    set(link_flags "-flto -lidbfs.js -s ASYNCIFY -s ASYNCIFY_IGNORE_INDIRECT=1 -s ASYNCIFY_IMPORTS='[exit]' -s ENVIRONMENT=web -s EXIT_RUNTIME=1 -s EXPORTED_FUNCTIONS='[_main, _setSavePath]' -s INVOKE_RUN=0 -s SINGLE_FILE=1 --closure 1 --embed-file ${data_dir}/death_royal.txt@/data/death_royal.txt --embed-file ${data_dir}/death_tomb.txt@/data/death_tomb.txt --embed-file ${data_dir}/help.txt@/data/help.txt --embed-file ${data_dir}/help_wizard.txt@/data/help_wizard.txt --embed-file ${data_dir}/rl_help.txt@/data/rl_help.txt --embed-file ${data_dir}/rl_help_wizard.txt@/data/rl_help_wizard.txt --embed-file ${data_dir}/splash.txt@/data/splash.txt --embed-file ${data_dir}/versions.txt@/data/versions.txt --embed-file ${data_dir}/welcome.txt@/data/welcome.txt --embed-file ${build_dir}/LICENSE@/LICENCE --pre-js ${PROJECT_SOURCE_DIR}/src/browser_io.js")
    set(link_depends "${PROJECT_SOURCE_DIR}/src/browser_io.js;${PROJECT_SOURCE_DIR}/src/numoria.html")
    set_target_properties(numoria PROPERTIES LINK_DEPENDS "${link_depends}")
    set_target_properties(numoria PROPERTIES LINK_FLAGS "${link_flags}")
else ()
    find_package(Curses REQUIRED)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
endif ()

include_directories("${CMAKE_BINARY_DIR}/${build_dir}")
