if (EMSCRIPTEN)
    set(PDC_PORT "sdl2")
    include(ExternalProjects/PDCursesMod)
    add_dependencies(numoria pdcurses)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
elseif ("${NUMORIA_BACKEND}" STREQUAL "pdc")
    include(ExternalProjects/PDCursesMod)
    add_dependencies(numoria pdcurses)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
elseif ("${NUMORIA_BACKEND}" STREQUAL "ncurses")
    set(CURSES_NEED_NCURSES TRUE)
    find_package(Curses REQUIRED)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
else ()
    find_package(Curses REQUIRED)
    include_directories(${CURSES_INCLUDE_DIR})
    set(linked_libs ${CURSES_LIBRARIES})
endif ()

include_directories("${CMAKE_BINARY_DIR}/${build_dir}")
